Removes the provider setting and improves the Readme
terraform-alicloud-modules/terraform-alicloud-ram pull request #10
Opened 2021-11-15 11:19 UTC by china-1947

2021-12-24 10:49 UTC, xiaozhu36 requested changes

2021-12-24 10:49 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  source              = "../../modules/ram-account"
这个source不对

2021-12-24 10:49 UTC, xiaozhu36 commented on examples/complete/variables.tf
> +}
这些参数不全

2021-12-28 03:32 UTC, Wanghx0991 commented on README-CN.md
> +本Module从版本v1.3.0开始已经移除掉如下的 provider 的显示设置：
本Module从版本v1.3.0开始已经移除如下的 provider 的显式设置：

2021-12-28 03:32 UTC, Wanghx0991 commented on modules/ram-account/variables.tf
> +  description = "(Deprecated from version 1.3.0)The region used to launch this module resources."
1.4.0

2021-12-28 03:32 UTC, Wanghx0991 commented on modules/ram-account/variables.tf
> +  description = "(Deprecated from version 1.3.0)The profile name as set in the shared credentials file. If not set, it will be sourced from the ALICLOUD_PROFILE environment variable."
1.4.0

2021-12-28 03:32 UTC, Wanghx0991 commented on modules/ram-account/variables.tf
> +  description = "(Deprecated from version 1.3.0)The profile name as set in the shared credentials file. If not set, it will be sourced from the ALICLOUD_PROFILE environment variable."
整体改下

2021-12-28 03:32 UTC, Wanghx0991 commented on modules/ram-assumable-role/variables.tf
> +  description = "(Deprecated from version 1.3.0)The region used to launch this module resources."
1.4.0, 整体改下

2021-12-28 03:32 UTC, Wanghx0991 commented on modules/ram-assumable-roles/variables.tf
> +  description = "(Deprecated from version 1.3.0)The region used to launch this module resources."
1.4.0

2021-12-28 03:32 UTC, Wanghx0991 commented on modules/ram-group-with-assumable-roles-policy/variables.tf
> +  description = "(Deprecated from version 1.3.0)The region used to launch this module resources."
1.4.0

2021-12-28 03:32 UTC, Wanghx0991 commented on modules/ram-user/variables.tf
> +  description = "(Deprecated from version 1.3.0)The region used to launch this module resources."
1.4.0

2021-12-28 03:32 UTC, Wanghx0991 commented on examples/complete/tfvars/01-update.tfvars
> +#variables for ram-account
https://github.com/terraform-alicloud-modules/terraform-alicloud-ram/blob/master/modules/ram-account/main.tf

2021-12-28 07:09 UTC, china-1947 commented on README-CN.md
> +本Module从版本v1.3.0开始已经移除掉如下的 provider 的显示设置：
这个没错，就是1.2.0  版本修改的

2021-12-31 03:57 UTC, Wanghx0991 commented on examples/complete/variables.tf
> +variable "is_reader" {
unused

2021-12-31 03:57 UTC, Wanghx0991 commented on examples/complete/variables.tf
> +variable "get_caller_identity" {
如果不支持更改complete/main.tf里写死

2021-12-31 03:57 UTC, Wanghx0991 commented on examples/complete/variables.tf
> +variable "create_account_password_policy" {
如果不支持更改complete/main.tf里写死

2021-12-31 03:57 UTC, Wanghx0991 commented on examples/complete/variables.tf
> +variable "name" {
这个也不支持更改么?

2021-12-31 03:57 UTC, Wanghx0991 commented on main.tf
> -
远端已经没有了啊, pull rebase 下

2021-12-31 03:57 UTC, Wanghx0991 commented on modules/ram-account/main.tf
> -  version                 = ">=1.64.0"
远端都已经删除了啊

2022-01-05 02:34 UTC, xiaozhu36 requested changes

2022-01-05 02:34 UTC, xiaozhu36 commented on examples/complete/main.tf
> +module "ram_account" {
这个先不用

2022-01-05 02:34 UTC, xiaozhu36 commented on examples/complete/main.tf
> +}
测试case还是不全
main.tf 中总共有 四个开关，对应到你的这个example 中，也应该有四个 module 的case

2022-01-05 02:34 UTC, xiaozhu36 commented on .gitignore
>  *.tfstate
针对你的这个case，gitignore 中应该增加上 对 secret.txt 的过滤

2022-01-05 09:19 UTC, xiaozhu36 commented on versions.tf
>  }
provider 的版本

2022-01-05 09:23 UTC, xiaozhu36 commented on examples/complete/main.tf
> +}
虽然四个开关有了，但是参数没有覆盖全。针对这个case，应该这样写：
1）指定一个name创建一个user；2）用 1）中创建的user 去创建一个login profile；3）用1）中创建的user去创建 access key；4）用 1）中创建的user 去admin的attachment；5）用 1）中创建的user 去创建 reader的attachment

2022-01-06 10:55 UTC, xiaozhu36 requested changes

2022-01-06 10:55 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  is_admin                      = false
你这个也不是按照我给你说的那种方式改的啊，相互之间没有关联啊

2022-01-07 02:00 UTC, xiaozhu36 requested changes

2022-01-07 02:00 UTC, xiaozhu36 commented on versions.tf
> +      version = ">= 1.123.1"
为啥是 1.123.1

2022-01-07 02:11 UTC, china-1947 commented on examples/complete/variables.tf
> +variable "name" {
在 examples/complete/tfvars/01-update.tfvars   文件 name 参数 中已支持修改了

2022-01-10 02:32 UTC, xiaozhu36 requested changes

2022-01-10 02:32 UTC, xiaozhu36 commented on variables.tf
> +  description = "Whether to create ram user."
改成 create_user

2022-01-10 02:32 UTC, xiaozhu36 commented on versions.tf
> +      version = ">= 1.3.0"
这个改成 1.56.0

2022-01-10 02:32 UTC, xiaozhu36 commented on variables.tf
> +  description = "The name of an existing RAM group. If set, 'create' will be ignored."
1. ˙这个表示的是 user name ，不是 group name
2. 逻辑反了，应该是 当 create_user 为true 的时候，这个参数将会被忽略
3.  这个参数不应该单独设置，因为上面已经有 name 来表示 user name了，直接用那个就行

2022-01-10 02:32 UTC, xiaozhu36 commented on main.tf
> +  count = local.create ? 1 : 0
这个地方的判断直接用 var.create_user

2022-01-11 09:36 UTC, xiaozhu36 requested changes

2022-01-11 09:36 UTC, xiaozhu36 commented on variables.tf
> +variable "user_name" {
这个名字不要改了

2022-01-11 10:23 UTC, xiaozhu36 requested changes

2022-01-11 10:23 UTC, xiaozhu36 commented on variables.tf
> +  default     = false
原来没有这个值，现在加上这个开关后，默认值应该是 true

2022-01-11 10:41 UTC, merged